LANGUAGES = {
    "Afrikaans": "af",
    "azərbaycan": "az",
    "Bahasa Indonesia": "id",
    "Bahasa Melayu": "ms",
    "bosanski": "bs",
    "català": "ca",
    "Čeština": "cs",
    "Dansk": "da",
    "Deutsch (Deutschland)": "de",
    "eesti": "et",
    "English (United States)": "en",
    "Español (España)": "es",
    "Español (Latinoamérica)": "es-419",
    "euskara": "eu",
    "Filipino": "fil",
    "Français (France)": "fr",
    "galego": "gl",
    "Hrvatski": "hr",
    "isiZulu": "zu",
    "íslenska": "is",
    "Italiano": "it",
    "Kiswahili": "sw",
    "latviešu": "lv",
    "lietuvių": "lt",
    "magyar": "hu",
    "Nederlands": "nl",
    "norsk": "no",
    "oʻzbekcha": "uz",
    "polski": "pl",
    "Português (Brasil)": "pt-BR",
    "Português (Portugal)": "pt-PT",
    "română": "ro",
    "shqip": "sq",
    "Slovenčina": "sk",
    "slovenščina": "sl",
    "Suomi": "fi",
    "Svenska": "sv",
    "Tiếng Việt": "vi",
    "Türkçe": "tr",
    "Ελληνικά": "el",
    "български": "bg",
    "кыргызча": "ky",
    "қазақ тілі": "kk",
    "македонски": "mk",
    "монгол": "mn",
    "Русский": "ru",
    "српски (ћирилица)": "sr",
    "Українська": "uk",
    "ქართული": "ka",
    "հայերեն": "hy",
    "עברית": "iw",
    "اردو": "ur",
    "العربية": "ar",
    "فارسی": "fa",
    "አማርኛ": "am",
    "नेपाली": "ne",
    "हिन्दी": "hi",
    "मराठी": "mr",
    "বাংলা": "bn",
    "ਪੰਜਾਬੀ": "pa",
    "ગુજરાતી": "gu",
    "தமிழ்": "ta",
    "తెలుగు": "te",
    "ಕನ್ನಡ": "kn",
    "മലയാളം": "ml",
    "සිංහල": "si",
    "ไทย": "th",
    "ລາວ": "lo",
    "ဗမာ": "my",
    "ខ្មែរ": "km",
    "한국어": "ko",
    "日本語": "ja",
    "简体中文": "zh-CN",
    "繁體中文": "zh-TW",
}

COUNTRIES = {
    "Afghanistan": "AF",
    "Albania": "AL",
    "Algeria": "DZ",
    "American Samoa": "AS",
    "Andorra": "AD",
    "Angola": "AO",
    "Antigua & Barbuda": "AG",
    "Argentina": "AR",
    "Armenia": "AM",
    "Australia": "AU",
    "Austria": "AT",
    "Azerbaijan": "AZ",
    "Bahamas": "BS",
    "Bahrain": "BH",
    "Bangladesh": "BD",
    "Belarus": "BY",
    "Belgium": "BE",
    "Belize": "BZ",
    "Benin": "BJ",
    "Bhutan": "BT",
    "Bolivia": "BO",
    "Bosnia & Herzegovina": "BA",
    "Botswana": "BW",
    "Brazil": "BR",
    "Brunei": "BN",
    "Bulgaria": "BG",
    "Burkina Faso": "BF",
    "Burundi": "BI",
    "Cambodia": "KH",
    "Cameroon": "CM",
    "Canada": "CA",
    "Cape Verde": "CV",
    "Central African Republic": "CF",
    "Chad": "TD",
    "Chile": "CL",
    "Colombia": "CO",
    "Congo - Brazzaville": "CG",
    "Congo - Kinshasa": "CD",
    "Cook Islands": "CK",
    "Costa Rica": "CR",
    "Côte d’Ivoire": "CI",
    "Croatia": "HR",
    "Cuba": "CU",
    "Cyprus": "CY",
    "Czechia": "CZ",
    "Denmark": "DK",
    "Djibouti": "DJ",
    "Dominica": "DM",
    "Dominican Republic": "DO",
    "Ecuador": "EC",
    "Egypt": "EG",
    "El Salvador": "SV",
    "Estonia": "EE",
    "Ethiopia": "ET",
    "Fiji": "FJ",
    "Finland": "FI",
    "France": "FR",
    "Gabon": "GA",
    "Gambia": "GM",
    "Georgia": "GE",
    "Germany": "DE",
    "Ghana": "GH",
    "Gibraltar": "GI",
    "Greece": "GR",
    "Greenland": "GL",
    "Guatemala": "GT",
    "Guernsey": "GG",
    "Guyana": "GY",
    "Haiti": "HT",
    "Honduras": "HN",
    "Hong Kong": "HK",
    "Hungary": "HU",
    "Iceland": "IS",
    "India": "IN",
    "Indonesia": "ID",
    "Iraq": "IQ",
    "Ireland": "IE",
    "Isle of Man": "IM",
    "Israel": "IL",
    "Italy": "IT",
    "Jamaica": "JM",
    "Japan": "JP",
    "Jersey": "JE",
    "Jordan": "JO",
    "Kazakhstan": "KZ",
    "Kenya": "KE",
    "Kiribati": "KI",
    "Kuwait": "KW",
    "Kyrgyzstan": "KG",
    "Laos": "LA",
    "Latvia": "LV",
    "Lebanon": "LB",
    "Lesotho": "LS",
    "Libya": "LY",
    "Liechtenstein": "LI",
    "Lithuania": "LT",
    "Luxembourg": "LU",
    "Madagascar": "MG",
    "Malawi": "MW",
    "Malaysia": "MY",
    "Maldives": "MV",
    "Mali": "ML",
    "Malta": "MT",
    "Mauritius": "MU",
    "Mexico": "MX",
    "Micronesia": "FM",
    "Moldova": "MD",
    "Mongolia": "MN",
    "Montenegro": "ME",
    "Morocco": "MA",
    "Mozambique": "MZ",
    "Myanmar (Burma)": "MM",
    "Namibia": "NA",
    "Nauru": "NR",
    "Nepal": "NP",
    "Netherlands": "NL",
    "New Zealand": "NZ",
    "Nicaragua": "NI",
    "Niger": "NE",
    "Nigeria": "NG",
    "Niue": "NU",
    "North Macedonia": "MK",
    "Norway": "NO",
    "Oman": "OM",
    "Pakistan": "PK",
    "Palestine": "PS",
    "Panama": "PA",
    "Papua New Guinea": "PG",
    "Paraguay": "PY",
    "Peru": "PE",
    "Philippines": "PH",
    "Pitcairn Islands": "PN",
    "Poland": "PL",
    "Portugal": "PT",
    "Puerto Rico": "PR",
    "Qatar": "QA",
    "Romania": "RO",
    "Russia": "RU",
    "Rwanda": "RW",
    "Samoa": "WS",
    "San Marino": "SM",
    "São Tomé & Príncipe": "ST",
    "Saudi Arabia": "SA",
    "Senegal": "SN",
    "Serbia": "RS",
    "Seychelles": "SC",
    "Sierra Leone": "SL",
    "Singapore": "SG",
    "Slovakia": "SK",
    "Slovenia": "SI",
    "Solomon Islands": "SB",
    "Somalia": "SO",
    "South Africa": "ZA",
    "South Korea": "KR",
    "Spain": "ES",
    "Sri Lanka": "LK",
    "St. Helena": "SH",
    "St. Vincent & Grenadines": "VC",
    "Suriname": "SR",
    "Sweden": "SE",
    "Switzerland": "CH",
    "Taiwan": "TW",
    "Tajikistan": "TJ",
    "Tanzania": "TZ",
    "Thailand": "TH",
    "Timor-Leste": "TL",
    "Togo": "TG",
    "Tonga": "TO",
    "Trinidad & Tobago": "TT",
    "Tunisia": "TN",
    "Türkiye": "TR",
    "Turkmenistan": "TM",
    "U.S. Virgin Islands": "VI",
    "Uganda": "UG",
    "Ukraine": "UA",
    "United Arab Emirates": "AE",
    "United Kingdom": "GB",
    "United States": "US",
    "Uruguay": "UY",
    "Uzbekistan": "UZ",
    "Vanuatu": "VU",
    "Venezuela": "VE",
    "Vietnam": "VN",
    "Zambia": "ZM",
    "Zimbabwe": "ZW",
}

SHORT_LANGUAGES = [
    "af",
    "agq",
    "ak",
    "am",
    "ar",
    "as",
    "asa",
    "ast",
    "az",
    "bas",
    "be",
    "bem",
    "bez",
    "bg",
    "bm",
    "bn",
    "bo",
    "br",
    "brx",
    "bs",
    "ca",
    "ccp",
    "ce",
    "cgg",
    "chr",
    "ckb",
    "cs",
    "cu",
    "cy",
    "da",
    "dav",
    "de",
    "dje",
    "dsb",
    "dua",
    "dyo",
    "dz",
    "ebu",
    "ee",
    "el",
    "en",
    "eo",
    "es",
    "et",
    "eu",
    "ewo",
    "fa",
    "ff",
    "fi",
    "fil",
    "fo",
    "fr",
    "fur",
    "fy",
    "ga",
    "gd",
    "gl",
    "gsw",
    "gu",
    "guz",
    "gv",
    "ha",
    "haw",
    "he",
    "hi",
    "hr",
    "hsb",
    "hu",
    "hy",
    "id",
    "ig",
    "ii",
    "is",
    "it",
    "ja",
    "jgo",
    "jmc",
    "ka",
    "kab",
    "kam",
    "kde",
    "kea",
    "khq",
    "ki",
    "kk",
    "kkj",
    "kl",
    "kln",
    "km",
    "kn",
    "ko",
    "kok",
    "ks",
    "ksb",
    "ksf",
    "ksh",
    "kw",
    "ky",
    "lag",
    "lb",
    "lg",
    "lkt",
    "ln",
    "lo",
    "lrc",
    "lt",
    "lu",
    "luo",
    "luy",
    "lv",
    "mas",
    "mer",
    "mfe",
    "mg",
    "mgh",
    "mgo",
    "mk",
    "ml",
    "mn",
    "mr",
    "ms",
    "mt",
    "mua",
    "my",
    "mzn",
    "naq",
    "nb",
    "nd",
    "nds",
    "ne",
    "nl",
    "nmg",
    "nn",
    "nnh",
    "no",
    "nus",
    "nyn",
    "om",
    "or",
    "os",
    "pa",
    "pl",
    "prg",
    "ps",
    "pt",
    "qu",
    "rm",
    "rn",
    "ro",
    "rof",
    "ru",
    "rw",
    "rwk",
    "sa",
    "sah",
    "saq",
    "sbp",
    "sd",
    "se",
    "seh",
    "ses",
    "sg",
    "shi",
    "si",
    "sk",
    "sl",
    "smn",
    "sn",
    "so",
    "sq",
    "sr",
    "sv",
    "sw",
    "sy",
    "ta",
    "te",
    "teo",
    "tg",
    "th",
    "ti",
    "tk",
    "to",
    "tr",
    "tt",
    "twq",
    "tzm",
    "ug",
    "uk",
    "ur",
    "uz",
    "vai",
    "vi",
    "vo",
    "vun",
    "wae",
    "wo",
    "xog",
    "yav",
    "yi",
    "yo",
    "yue",
    "zgh",
    "zh",
    "zu",
]

ratings = [
    "Any rating",
    "2.0+",
    "2.5+",
    "3.0+",
    "3.5+",
    "4.0+",
    "4.5+"
]
